import '@/styles/globals.css';

import { Inter as FontSans } from 'next/font/google';
import type { Metadata } from 'next';
import { ResponsiveHeader } from '@/components/responsive-header';
import { RootLayoutProps } from '@/types/layout';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Dan Wise',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <div className='flex flex-col min-h-screen'>
            <ResponsiveHeader />
            <main className='flex-grow container mx-auto px-4 py-8'>
              {children}
            </main>
            <Toaster />
            <footer className='border-t'>
              <div className='container mx-auto px-4 py-4 text-center'>
                © {new Date().getFullYear()} Dan Wise. All rights reserved.
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
